import javalib.impworld.*;
import javalib.worldimages.*;

// runs seam carving on an image
class World {
  // placeholder code for understanding
  WorldImage image = new FromFileImage("");

  // turn image into a grid of pixels
  // using this method to help
  // getColorAt(int x, int y)
  // Grid imageGrid = new Grid();

  // the image size 
  // WorldImage carvedImage = new ComputedPixelImage(int width, int height);
  // set the pixel colors using this method
  // setPixel(int x, int y, Color c)

  // save image as a file
  // saveImage(String filename)
}
